[project]
name = "house-price-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sara692", email = "saraomran433@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.6.0",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "prometheus-client>=0.26.0",
    "prometheus-fastapi-instrumentator>=8.1.0",
    "scikit-learn>=1.9.1",
]

[project.scripts]
house-price-prediction = "house_price_prediction:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "house_price"
